micronaut:
  application:
    name: pixKeyManagerGrpc
datasources:
  default:
    url: ${DB_URL:`jdbc:postgresql://localhost:5432/postgres`}
    driverClassName: org.postgresql.Driver
    username: ${DB_USER:gustavo}
    password: ${DB_PASSWORD:12345678}
    schema-generate: CREATE_DROP
    dialect: POSTGRES
jpa.default.properties.hibernate.hbm2ddl.auto: update

#variaveis
app:
  bcbUrl: ${BCB_URL:`http://localhost:8082/api/v1/pix/keys`}
  erpUrl: ${ERP_URL:`http://localhost:9091/api/v1`}